apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: petclinic
spec:
  host: argocd-java-demo.apps-crc.testing
status:
  ingress:
  - conditions:
    host: argocd-java-demo.apps-crc.testing
    routerCanonicalHostname: apps-crc.testing
    routerName: default
    wildcardPolicy: None