apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: "2019-12-07T16:23:08Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: nexus
    template: nexus2-persistent-template
  name: nexus-pv
  namespace: cicd2
  resourceVersion: "89940"
  selfLink: /api/v1/namespaces/cicd2/persistentvolumeclaims/nexus-pv
  uid: db06fda3-190d-11ea-8cae-0ef0e3c74fbe
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  volumeName: pv0023
status:
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  - ReadOnlyMany
  capacity:
    storage: 100Gi
  phase: Bound
