apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: nexus
    template: nexus2-persistent-template
  name: nexus
  namespace: cicd
spec:
  host: nexus-cicd2.apps-crc.testing
  port:
    targetPort: 8081-tcp
  subdomain: ""
  to:
    kind: Service
    name: nexus
    weight: 100
  wildcardPolicy: None
status:
  ingress:
    host: nexus-cicd2.apps-crc.testing
    routerCanonicalHostname: apps-crc.testing
    routerName: default
    wildcardPolicy: None
